import React, { useState } from "react";
import NavigationBar from "../components/homepage/NavigationBar";
import Footer from "../components/homepage/Footer";

export default function WorkaziLegal () {
  const [activeTab, setActiveTab] = useState("privacy");

  return (
    <div className="min-h-screen bg-white  text-slate-800 flex flex-col justify-between">
      <div className="bg-linear-to-r from-green-50 via-lime-50 to-white border-b border-slate-200/60 pb-12">
        <NavigationBar />
        <div className="max-w-5xl mx-auto px-4 text-center mt-10">
          <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
            Workazi Privacy Policy and Terms of Use
          </h1>
          <p className="text-sm text-slate-600 mt-2">
            Effective Date: <span className="font-semibold">15th May 2025</span>
          </p>

          <div className="flex justify-center gap-3 mt-8">
            <button
              onClick={() => setActiveTab("privacy")}
              className={`px-6 py-2.5 rounded-full text-sm font-semibold transition-all cursor-pointer ${
                activeTab === "privacy"
                  ? "bg-emerald-600 text-white shadow-md"
                  : "bg-white/80 text-slate-700 hover:bg-white border border-slate-200"
              }`}
            >
              Privacy Policy
            </button>
            <button
              onClick={() => setActiveTab("terms")}
              className={`px-6 py-2.5 rounded-full text-sm font-semibold transition-all cursor-pointer ${
                activeTab === "terms"
                  ? "bg-emerald-600 text-white shadow-md"
                  : "bg-white/80 text-slate-700 hover:bg-white border border-slate-200"
              }`}
            >
              Terms and Conditions of Use
            </button>
          </div>
        </div>
      </div>

      <main className="max-w-5xl mx-auto px-4 sm:px-6 py-12 w-full grow text-slate-700 leading-relaxed text-sm space-y-8">
        {activeTab === "privacy" ? (
          <article className="space-y-6">
            <header className="border-b border-slate-200 pb-4">
              <h2 className="text-2xl font-bold text-slate-900">Privacy Policy</h2>
              <p className="text-slate-600 text-xs mt-1">
                <strong>WORKAZI PRIVACY POLICY AND TERMS OF USE</strong><br />
                <strong>Effective Date:</strong> 15th May 2025<br />
                <strong>Controller & Data Protection Officer:</strong> Joan Nabusoba<br />
                <strong>Contact:</strong> team@workazi.ke
              </p>
            </header>

            <section className="space-y-4">
              <p>
                Our Privacy Policy was last updated on 5th May 2025. We are committed to protecting your privacy, hence this Privacy Policy describes Our policies and procedures on the collection, use and disclosure of your personal information when you use the workazi App Service and tells you about your privacy rights and how the law protects you.
              </p>
              <p>
                We use your Personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.
              </p>
              <p>
                This Privacy Policy applies to our app, and its associated subdomains (collectively, our “Service”) alongside our application, workazi. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
              </p>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">Definitions and key terms</h3>
              <p>To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
                <li><strong>Company:</strong> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Dimogare (2023) Ltd., that is responsible for your information under this Privacy Policy.</li>
                <li><strong>Country:</strong> where workazi or the owners/founders of workazi are based, in this case is Kenya</li>
                <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the workazi Service to manage the relationships with your consumers or service users.</li>
                <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit workazi and use the services.</li>
                <li><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
                <li><strong>Personnel:</strong> refers to those individuals who are employed by workazi or are under contract to perform a service on behalf of one of the parties.</li>
                <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number or passport number — allows for the identification or identifiability of a natural</li>
                <li><strong>Service:</strong> refers to the service provided by workazi app as described in the relative terms and on this platform.</li>
                <li><strong>Third-party service:</strong> refers to sponsors, promotional and marketing partners, advertisers, and others who provide our content or whose products or services we think may interest you.</li>
                <li><strong>App/Application:</strong> workazi app, refers to the SOFTWARE PRODUCT identified</li>
                <li><strong>You:</strong> a person or entity that is registered with workazi to use the</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h3 className="text-lg font-bold text-slate-900">1. Information We Collect</h3>
              <p>We collect information from you when you visit our app, register on our site, place an order, subscribe, respond to a survey or fill out a form.</p>
              <p>To provide and enhance our services, we collect the following:</p>

              <div className="space-y-3">
                <h4 className="font-semibold text-slate-900">Personal Information:</h4>
                <p>While using Our Service, we may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally, identifiable information may include, but is not limited to:</p>
                <ul className="list-disc pl-6 space-y-1">
                  <li>Names/ Usernames, email addresses, Mailing addresses, telephone numbers, photos</li>
                  <li>Age</li>
                  <li>Government-issued ID number</li>
                  <li>Location</li>
                  <li>Academic and professional documents</li>
                  <li>Employment history, Job titles, skills, and job preferences</li>
                  <li>Payment and billing information, billing addresses</li>
                </ul>
              </div>

              <div className="space-y-3">
                <h4 className="font-semibold text-slate-900">Usage Data:</h4>
                <p>
                  Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device’s Internet Protocol address (e.g. browser information address, device type, OS), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data:- App usage behavior (pages visited, features used) and Interaction logs (errors, session duration, etc.)
                </p>
                <p>
                  When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                </p>
                <p>
                  We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
                </p>
              </div>

              <div className="space-y-3">
                <h4 className="font-semibold text-slate-900">Information Collected while Using the Application:</h4>
                <p>While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:</p>
                <ul className="list-disc pl-6 space-y-1">
                  <li>Information regarding your location.</li>
                </ul>
                <p>
                  We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company’s servers and/or a Service Provider’s server or it may be simply stored on Your device.
                </p>
              </div>

              <div className="space-y-2">
                <h4 className="font-semibold text-slate-900">1. Location Data:</h4>
                <p>We collect location for job matching.</p>
                <p>Location data helps to create an accurate representation of your interests, and this can be used to bring more targeted and relevant jobs to potential employers and job seekers to relevant contractors/ employers</p>
              </div>

              <div className="space-y-2">
                <h4 className="font-semibold text-slate-900">2. Communications:</h4>
                <p>Messages exchanged within the app between workers and employers.</p>
                <p><strong>Phonebook (Contacts list):</strong> Your contacts list allows the platform to be much easier to use by the user, since accessing your contacts from the app makes you save tons of time.</p>
              </div>
            </section>

            <section className="space-y-4">
              <h3 className="text-lg font-bold text-slate-900">2. How We Use Your Information</h3>
              <p><strong>Use of Your Personal Data</strong></p>
              <p>The Dimogare may use Personal Data Workazi’s services for the following purposes:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                <li>To create manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                <li>Process membership and subscription payments.</li>
                <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application’s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                <li>Facilitate in-app communication between users.</li>
                <li>To provide You with Match job seekers with relevant job listings, news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
                <li>Send transactional updates and, with consent, marketing messages</li>
                <li>To manage Your requests: To attend and manage Your requests to Us.</li>
                <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
                <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
                <li>Conduct analytics and app improvements</li>
                <li>Comply with legal and regulatory obligations</li>
              </ul>

              <p>We may share Your personal information in the following situations:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, for payment processing, to contact You.</li>
                <li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
                <li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
                <li><strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
                <li><strong>With other users:</strong> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
                <li><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h3 className="text-lg font-bold text-slate-900">How You Can Opt Out of Data Sharing, Targeted Advertising, and Profiling</h3>
              <p>
                At Workazi, we believe in transparency and giving you control over your personal information. Depending on where you live, you may have the right to opt-out of certain uses of your data, including:
              </p>
              <ul className="list-disc pl-6 space-y-1">
                <li>The sale or sharing of your personal data with third parties</li>
                <li>The use of your data for targeted advertising</li>
                <li>Profiling that produces legal or similarly significant effects on you (e.g., automated decisions about hiring or financial services)</li>
              </ul>

              <h4 className="font-semibold text-slate-900 pt-2">How to Opt Out</h4>
              <p>You can exercise your opt-out rights by any of the following methods:</p>
              <p><strong>Privacy Settings Dashboard:</strong> Visit Workazi app settings and manage your privacy preferences.</p>
              <p><strong>Email Request:</strong> Send an email to team@workazi.ke with the subject line “Opt-Out Request” and specify what you would like to opt out of.</p>
              <p><strong>Global Privacy Control (GPC):</strong> If your browser supports GPC signals, we honor such signals as a valid request to opt-out of the sale or sharing of your personal data, where legally required.</p>
              <p>We will respond to your request within the timeframe required by law and confirm any actions taken.</p>

              <h4 className="font-semibold text-slate-900 pt-2">International Users – Your Rights</h4>
              <p>Users in specific jurisdictions may have additional opt-out rights:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>Virginia, USA (VCDPA):</strong> You may opt out of targeted advertising, sale of personal data, and profiling (Va. Code Ann. §§ 59.1-577, 578).</li>
                <li><strong>Japan (APPI):</strong> You may restrict the provision of your personal data to third parties under Article 27(2)(vi).</li>
                <li><strong>South Korea (PIPA):</strong> You are entitled to clear explanations and opt-out mechanisms per Article 30(1).</li>
                <li><strong>South Africa (POPIA):</strong> You will be informed when personal information is collected and have a right to object to its processing per Section 18(1)(h)(iv).</li>
              </ul>
              <p>If you have any questions about your privacy rights or need help with your opt-out request, please contact us at team@workazi.ke.</p>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">Data Controller Information</h3>
              <p>
                For the purposes of applicable data protection laws, including the General Data Protection Regulation (GDPR), the Personal Information Protection Law (PIPL) of the People’s Republic of China, and other relevant privacy regulations, the entity responsible for the collection, use, and protection of your personal data is:
              </p>
              <p className="pl-4 border-l-2 border-emerald-500 font-mono text-xs">
                DIMOGARE(2023) Ltd.<br />
                Nairobi, Kenya<br />
                Email: team@workazi.ke<br />
                Phone: +254 117 052 267
              </p>
              <p>
                Workazi Ltd. is the data controller of your personal information. This means that we determine the purposes for which and the means by which your personal data is processed. If you have any questions about this policy or how we handle your personal data, or if you wish to exercise your data rights (such as access, correction, deletion, or objection), you may contact us at the email address provided above.
              </p>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">3. Legal Bases for Processing (GDPR and global compliance)</h3>
              <p>We rely on:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>Consent:</strong> for notifications and marketing</li>
                <li><strong>Contractual necessity:</strong> for account creation and service delivery</li>
                <li><strong>Legal obligation:</strong> for recordkeeping and law enforcement requests</li>
                <li><strong>Legitimate interests:</strong> for analytics and fraud prevention</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h3 className="text-lg font-bold text-slate-900">4. How We Share Your Information</h3>
              <p>The Company may disclose and share your Personal Data in the good faith belief that such action is necessary to:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Comply with a legal obligation</li>
                <li>Protect and defend the rights or property of the Company</li>
                <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                <li>Protect the personal safety of Users of the Service or the public</li>
                <li>Protect against legal liability</li>
              </ul>
              <p>
                Under certain circumstances of law enforcement, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
              </p>
              <p>
                <strong>Business Transactions:</strong> If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
              </p>
              <p>We may share your data with:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>Other Users:</strong> For job applications, your profile info is shared with employers.</li>
                <li><strong>Service Providers:</strong> Firebase (Google) for push notifications and analytics.</li>
                <li><strong>Legal Authorities:</strong> Where required to comply with laws or enforce our terms.</li>
              </ul>
              <p>We do not sell your personal data.</p>
              <p>However, as per CCPA and VCDPA definitions (as adopted herewith), you have the right to opt-out of targeted advertising and data sharing used for profiling.</p>
            </section>

            <section className="space-y-4">
              <h3 className="text-lg font-bold text-slate-900">5. Your Privacy Rights</h3>
              <p>Depending on your location, you may have the following rights:</p>

              <div className="space-y-2">
                <h4 className="font-semibold text-slate-900">a. General User Rights (Global)</h4>
                <ul className="list-disc pl-6 space-y-1">
                  <li>Right to access, correct, or delete your data</li>
                  <li>Right to withdraw consent at any time</li>
                  <li>Right to object to or restrict processing</li>
                  <li>Right to data portability</li>
                </ul>
              </div>

              <div className="space-y-2">
                <h4 className="font-semibold text-slate-900">b. California Residents (CCPA/CPRA) adopted herewith in this Privacy Policy</h4>
                <p>You have the right to:</p>
                <ul className="list-disc pl-6 space-y-1">
                  <li>Know what categories and specific personal information we collect</li>
                  <li>Know the purposes for which we use the data</li>
                  <li>Know whether your data is sold or shared (we do not sell data)</li>
                  <li>Opt out of the sale or sharing of personal information for cross-context behavioral advertising</li>
                  <li>Request deletion of your personal data</li>
                  <li>Limit use of sensitive personal information</li>
                </ul>
                <p>To exercise your rights, email team@workazi.ke. You can also designate an authorized agent.</p>
              </div>

              <div className="space-y-2">
                <h4 className="font-semibold text-slate-900">c. Virginia Residents (VCDPA) adopted herewith in this Privacy Policy</h4>
                <p>You have the right to:</p>
                <ul className="list-disc pl-6 space-y-1">
                  <li>Confirm whether we process your personal data</li>
                  <li>Access and obtain a copy of your personal data</li>
                  <li>Correct inaccuracies</li>
                  <li>Request deletion</li>
                  <li>Opt out of: Targeted advertising, Sale of personal data, Profiling in furtherance of decisions that produce legal or similarly significant effects</li>
                </ul>
                <p>To opt out, email team@workazi.ke</p>
              </div>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">6. How to Opt-Out of Targeted Ads or Data Sharing</h3>
              <p>You may opt out of data use for advertising or analytics by:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Contacting us directly at team@workazi.ke</li>
                <li>Turning off personalized ads in your device settings (Android/iOS)</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">7. Data Retention</h3>
              <p><strong>Retention of Your Personal Data:</strong> The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.</p>
              <p>We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
              <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
              <p>We retain your personal information as long as your account is active or required by law.</p>
              <p>Upon account deletion:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Financial records are retained for up to 7 years</li>
                <li>Some anonymized data may be retained for internal analysis</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">8. Data Security</h3>
              <p>We implement industry-standard security measures:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>HTTPS encryption</li>
                <li>Firebase secured backend</li>
                <li>Regular security audits</li>
              </ul>
              <p>The security of Your Personal Data is important to Us; However, no platform is 100% secure, and we encourage strong password practices. No method of transmission over the Internet, or method of electronic storage is 100% secure.</p>
              <p>While We strive to use commercially acceptable means to protect Your Personal Data, we cannot guarantee its absolute security.</p>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">9. Cookies and Tracking Technologies</h3>
              <p>We use tracking tools like cookies and analytics SDKs to:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Improve user experience</li>
                <li>Understand feature usage</li>
                <li>Enable targeted notifications (with your consent)</li>
              </ul>
              <p>You can manage tracking via device or browser settings.</p>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">10. Third-Party Services</h3>
              <p>Workazi uses:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Firebase (by Google) for push notifications, analytics, and crash logging</li>
                <li>Pesapal for payment processing</li>
                <li>Amazon lightsail to host django backend</li>
              </ul>
              <p>These services may process limited data under their own privacy policies. We recommend reviewing Google’s Privacy Policy.</p>
              <p><strong>Detailed Information on the Processing of Your Personal Data:</strong> these Service Providers We use may have access to Your Personal Data.</p>
              <p>These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.</p>
              <p><strong>Analytics</strong> We may use third-party Service providers to monitor and analyze the use of our Service.</p>
              <p><strong>Email Marketing</strong>, We may use Your Personal Data to contact You with newsletters, marketing or promotional materials and other information that may be of interest to You.</p>
              <p>You may opt-out of receiving any, or all, of these communications from Us by following the unsubscribe link or instructions provided in any email We send or by contacting Us.</p>
              <p><strong>Links to Other Websites</strong></p>
              <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, you will be directed to that third party’s site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
              <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party sites or services.</p>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">11. Transfer of Your Data</h3>
              <p>Your information, including Personal Data, is processed at the Company’s operating offices and in any other places where the parties involved in the processing are located.</p>
              <p>It means that this information may be transferred to — and maintained on — computers located outside of Your county, region, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
              <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
              <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
              <p><strong>Cross-Border Transfers:</strong> Your data may be processed outside your country, including but not limited to the United States, Kenya, or Europe. We take appropriate safeguards for international transfers, including standard contractual clauses where applicable.</p>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">12. Eligibility/Children’s Privacy</h3>
              <p>Workazi is not intended for users under 18.</p>
              <p>To use workazi you must be at least 18 years old or has parental consent. We do not knowingly collect data from minors without verifiable parental consent.</p>
              <p>By using our App, you represent and warrant the you meet the legibility requirements.</p>
              <p>If You are a parent or guardian and You are aware that your under 18 child has provided us with Personal Data, please contact Us.</p>
              <p>If We become aware that We have collected Personal Data from anyone under the age of 18 without verification of parental consent, We take steps to remove that information from Our servers.</p>
              <p>If We need to rely on consent as a legal basis for processing your information and the applicable law and regulations require consent from a parent, we may require your parent’s consent before we collect and use that information.</p>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">13. Political Neutrality</h3>
              <p>Dimogare as a responsible corporate citizen committed to civic engagement and public policies that support its business interests.</p>
              <p>Workazi App is a platform meant for the benefit of all stakeholders in the construction industry and other users of the App, therefore it is Non-aligned to any partisan politics.</p>
              <p>Any engagement with the any political process related to workazi services must be in a thoughtful and transparent way. Personalities in political field or events may be used for the benefit of making the youths and other job seekers aware of jobs by offered by contractors using the App.</p>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">14. Changes to This Policy</h3>
              <p>We may update and/ or change our Services and this policy periodically. Unless otherwise required by law, you will be notified through the app or email, and changes will be posted here with a new “Effective Date.”</p>
              <p>Then, subsequently, if you continue to use the Service, you will be bound by the updated Privacy Policy. If you do not want to agree to this or any updated Privacy Policy, you are entitled to consider and decide whether or not to delete your account.</p>
              <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">15. Consent</h3>
              <p>We’ve updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site or download workazi App and how it’s being used.</p>
              <p>By using our workazi App, registering an account, or making a subscription, you hereby consent to our Privacy Policy and agree to its terms.</p>
            </section>

            <section className="space-y-3 pt-4 border-t border-slate-200">
              <h3 className="text-lg font-bold text-slate-900">15. Contact Us</h3>
              <p>If you have any questions about this Privacy Policy, You can contact us:</p>
              <p>By visiting this page on our website:</p>
              <p>By sending us an email:</p>
              <p>For questions, requests, or complaints about your privacy rights, contact:</p>
              <p>
                <strong>Joan Nabusoba</strong><br />
                Email: team@workazi.ke<br />
                Role: Data Controller & Data Protection Officer
              </p>
            </section>
          </article>
        ) : (
          <article className="space-y-6">
            <header className="border-b border-slate-200 pb-4">
              <h2 className="text-2xl font-bold text-slate-900">Terms and Conditions of Use</h2>
            </header>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">1. Introduction</h3>
              <p>
                This Terms of Use Agreement (“Agreement”) governs your use of the Workazi application (“Application”). These Legal Terms constitute a legally binding agreement made between you, whether personally or on behalf of an entity and workazi App owners concerning your access to and use of the Services.
              </p>
              <p>
                By accessing or using the Services of Application, you acknowledge that you have read, understood, and agreed to be bound by all of these Legal Terms.
              </p>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">2. User Accounts</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Job Seekers:</strong> You must create an account to upload your details, certifications and search for job opportunities.</li>
                <li><strong>Freelancers job seekers:</strong> You must create an account to upload your details, certifications as self-employed individual who offer his/her skills and services on a project or contract basis, rather than being employed full-time by a single contractor.</li>
                <li><strong>Employers/contractors:</strong> You must create an account to view job seeker profiles and post jobs openings.</li>
                <li><strong>Single task employers:</strong> You must create an account to view job seeker profiles and seek employee for specific single or one-time tasks.</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">3. User Conduct and Prohibited Activities</h3>
              <p>You agree to use the Application in a lawful, ethical, and respectful manner.</p>
              <p>
                You may not access or use the Services for any purpose other than that for which we make the Services available. The Services may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us.
              </p>
              <p>As a user of the Services, you agree not to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Systematically retrieve data or other content from the Services to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.</li>
                <li>Systematically retrieve data or other content from the Services to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.</li>
                <li>Make any unauthorized use of the Services, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretenses.</li>
                <li>Circumvent, disable, or otherwise interfere with security-related features of the Services, including features that prevent or restrict the use or copying of any Content or enforce limitations on the use of the Services and/or the Content contained therein.</li>
                <li>Engage in unauthorized framing of or linking to the Services.</li>
                <li>Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords.</li>
                <li>Engage in fraudulent activities</li>
                <li>Make improper use of our support services or submit false reports of abuse or misconduct.</li>
                <li>Engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools.</li>
                <li>Interfere with, disrupt, or create an undue burden on the Services or the networks or services connected to the Services.</li>
                <li>Engage in Posting false or misleading information</li>
                <li>Attempt to impersonate another user or person or use the username of another user.</li>
                <li>Use any information obtained from the Services in order to harass, abuse, discriminate or harm other users or any another person.</li>
                <li>Use the Services as part of any effort to compete with us or otherwise use the Services and/or the Content for any revenue-generating endeavor or commercial enterprise.</li>
                <li>Except as permitted by applicable law, decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Services.</li>
                <li>Attempt to bypass any measures of the Services designed to prevent or restrict access to the Services, or any portion of the Services.</li>
                <li>Harass, annoy, intimidate, or threaten any of our employees or agents engaged in providing any portion of the Services to you.</li>
                <li>Delete the copyright or other proprietary rights notice from any Content.</li>
                <li>Copy or adapt the Services’ software, including but not limited to Flash, PHP, HTML, JavaScript, or other code.</li>
                <li>Upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material, including excessive use of capital letters and spamming (continuous posting of repetitive text), that interferes with any party’s uninterrupted use and enjoyment of the Services or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Services.</li>
                <li>Upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or transmission mechanism, including without limitation, clear graphics interchange formats (“gifs”), 1×1 pixels, web bugs, cookies, or other similar devices (sometimes referred to as “spyware” or “passive collection mechanisms” or “pcms”).</li>
                <li>Except as may be the result of standard search engine or Internet browser usage, use, launch, develop, or distribute any automated system, including without limitation, any spider, robot, cheat utility, scraper, or offline reader that accesses the Services, or using or launching any unauthorized script or other software.</li>
                <li>Disparage, tarnish, or otherwise harm, in our opinion, us and/or the Services.</li>
                <li>Use Workazi App to engage partisan political activities to gain political advantage and not intended for the benefit of making the youths and other job seekers aware of jobs by offered by contractors using the App.</li>
                <li>Use the Services in a manner inconsistent with any applicable laws or regulations.</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">4. Job Seekers</h3>
              <p>You agree to provide correct, accurate and up-to-date information and documentation in your profile.</p>
              <p>You understand that employers may use your information to evaluate your suitability for job openings.</p>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">5. Employers</h3>
              <p>You agree to use the Application to post legitimate job openings.</p>
              <p>You are responsible for reviewing job seeker profiles, verifying the authenticity/ validity of the certifications and qualifications in the job seekers profiles and making hiring decisions.</p>
            </section>

            <section className="space-y-4">
              <h3 className="text-lg font-bold text-slate-900">6. Intellectual Property</h3>
              <p>
                Dimogare (2023) Co. Ltd is the owner or the licensee of all intellectual property rights in workazi App Services, including all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics in the Services (collectively, the “Content”), as well as the trademarks, service marks, and logos contained therein (the “Marks”).
              </p>
              <p>
                The workazi Application and its content and Marks are protected by copyright, trademark laws and other intellectual property laws (and various other intellectual property rights and unfair competition laws) and treaties in Kenya and around the world.
              </p>
              <p>You shall not reproduce, modify, distribute, or exploit the Application without our prior written consent.</p>

              <h4 className="font-semibold text-slate-900 pt-2">Intellectual Property Rights of Others</h4>
              <p>
                We respect the intellectual property rights of others. If you believe that any material available on or through the Services infringes upon any copyright you own or control, please immediately notify us using the contact information provided below
              </p>
              <p>
                Please be advised that pursuant to law you may be held liable for damages if you make material misrepresentations in the Notification. Thus, if you are not sure that material located on or linked to by the Services infringes your copyright, you should consider first seeking legal advice.
              </p>
              <p>
                All Notifications should include the following information: (1) A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; (2) identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works on the Services are covered by the Notification, a representative list of such works on the Services; (3) identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material; (4) information reasonably sufficient to permit us to contact the complaining party, such as an address, telephone number, and, if available, an email address at which the complaining party may be contacted; (5) a statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and (6) a statement that the information in the notification is accurate, and that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed upon.
              </p>
            </section>

            <section className="space-y-3">
              <h3 className="text-lg font-bold text-slate-900">7. Disclaimer of Warranties</h3>
              <p>
                The services of the Application are provided on an “as is” and as-available basis without warranties of any kind. We do not guarantee the accuracy, completeness, or reliability of the information on the Application. You agree that your use of the services will be at your sole risk.
              </p>
              <p>
                To the fullest extent permitted by law, we disclaim all warranties, express or implied, in connection with the services and your use thereof, including, without limitation, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
              </p>
              <p>
                We make no warranties or representations about the accuracy or completeness of the services’ content or the content of any websites or mobile applications linked to the services and we will assume no liability or responsibility for any (1) errors, mistakes, or inaccuracies of content and materials, (2) personal injury or property damage, of any nature whatsoever, resulting from your access to and use of the services, (3) any unauthorized access to or use of our secure servers
              </p>
            </section>
          </article>
        )}
      </main>

      <Footer />
    </div>
  );
}